name: CI

on: repository_dispatch

jobs:
  updateImage:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_schema_release'

    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up npm
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        bash .openapi-generator/generate.sh $VERSION

    - name: "Set Commit Message"
      id: vars
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        echo ::set-output name=commit_message::"Update Schema to $VERSION"


    - name: "Commit and Push Changes"
      id: push
      env:
        COMMIT_MESSAGE: ${{ steps.vars.outputs.commit_message }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "$COMMIT_MESSAGE"
        git push